---
- hosts: all
  remote_user: root
  vars:
    - container_name: oracle-lens
    - image_name: oracle-lens
    # - ansible_ssh_private_key_file: "../oracle"
  tasks:
    - name: build container image
      command: "docker build -t {{image_name}} -f ../Dockerfile ../"
      delegate_to: 127.0.0.1

    - name: archive container image as a tarball
      command: "docker save -o {{image_name}}.tar {{image_name}}"
      delegate_to: 127.0.0.1

    - name: copy tarball to host
      copy:
        src: "{{ image_name }}.tar"
        dest: "./{{ image_name }}.tar"

    - name: load container from tarball
      docker_image:
        name: "{{ image_name }}"
        load_path: "./{{ image_name }}.tar"
        state: present
        source: load

    - name: start container with new version
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        network_mode: host
        restart_policy: unless-stopped
      register: deploy_service

    - name: prune docker on {{ansible_host}}
      shell: docker image prune -a --filter "until=72h" --force
      when:
        - deploy_service.container.State.Running

