name: Client App CI\CD

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ClientApp
        
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
      
      # Share artifact inside workflow
    - name: Share artifact inside workflow
      uses: actions/upload-artifact@v1
      with:
        name: react-github-actions-build
        path: dist
        
    - name: Copy via ssh
      uses: actions/download-artifact@v1
      with:
        name: react-github-actions-build
        remote: ${{ secrets.REMOTE_CLIENT_APP_TARGET }}
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}
