name: Install docker

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        # Required, playbook filepath
        playbook: deploy-docker.yml
        # Optional, directory where playbooks live
        directory: "/ci/"
        # Optional, SSH private key
        key: ${{secrets.REMOTE_SSH_KEY}}
        # Optional, literal inventory file contents
        inventory: |
          [all]
          ${{secrets.REMOTE_HOST}}
