name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1.x'
    - name: Dotnet Publish
      run: dotnet publish LeagueActivityBot.Host -c Release -o deploy
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: '/home/runner/work/Oracles-Lens/Oracles-Lens/deploy/appsettings.json'
      env:
        App.DbConnectionString: ${{ secrets.APP_DB_CONNTECTION_STRING }}
        App.Telegram.ApiKey: ${{ secrets.APP_TELEGRAM_API_KEY }}
        App.Telegram.ChatId: ${{ secrets.APP_TELEGRAM_CHAT_ID }}
        App.Telegram.LogChatId: ${{ secrets.APP_TELEGRAM_LOGCHAT_ID }}
        App.SummonerNames: ${{ secrets.APP_SUMMONER_NAMES }}
        Serilog.File.Path: ${{ secrets.APP_SUMMONER_NAMES }}
        
    - name: Copy via ssh
      uses: garygrossgarten/github-action-scp@v0.5.3
      with:
        local: /home/runner/work/Oracles-Lens/Oracles-Lens/deploy/
        remote: ${{ secrets.REMOTE_TARGET }}
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}
    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.3.0
      with:
        command: sudo service LeagueBot restart
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}
